kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: node:latest
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    commands:
      - npm install
      - npm run build
