import Head from "next/head";
import Image from "next/image";
import { remark } from 'remark'
import html from 'remark-html'
import fs from 'fs'
import path from 'path'
import styles from "../styles/Home.module.css";
import HeaderComponent from "../components/common/Header/header";
import FooterComponent from "../components/common/Footer/footer";

export default function Home({ meta, content }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent></HeaderComponent>
      

      

      <main className={styles.main}>
      <div dangerouslySetInnerHTML={{ __html: content }} />
      </main>

      <FooterComponent></FooterComponent>
    </div>
  );
}

export async function getStaticProps() {
  const fullPath = path.join(process.cwd(), 'pages', 'index.md')

  const fileContents = fs.readFileSync(fullPath,'utf8')
  const processedContent = await remark()
  .use(html)
  .process(fileContents)
  const contentHtml = processedContent.toString()


  return {
    props: {
      ...contentHtml,
      'content': contentHtml
    }
  }
}
